### ISSUE TITLE
numerl:inv/2 returns an incorrect result

### ISSUE THREAD

**Issue by jj1bdx** [tanguyl/numerl#10]
On both macOS 12.1 x86_64 and homebrew OpenBLAS (0.3.19) and Ubuntu 21.10 and64 with libopenblas-dev 0.3.13+ds-3:

```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [sharing-preserving]

Eshell V12.2  (abort with ^G)
1> L = numerl:matrix([[1,2],[3,4]]).
{matrix,2,2,
        <<0,0,0,0,0,0,240,63,0,0,0,0,0,0,0,64,0,0,0,0,0,0,8,64,0,
          ...>>}
2> Linv = numerl:inv(L).
{matrix,2,2,
        <<0,0,0,0,0,0,240,63,0,0,0,0,0,0,224,191,0,0,0,0,0,0,0,0,
          0,...>>}
3>  numerl:print(numerl:dot(L, Linv)).
'[[1.00000 0.00000][3.00000 -0.50000]]' %% <- an incorrect result, this should have been '[[1 0][0 1]]'
4> numerl:print(Linv).
'[[1.00000 -0.50000][0.00000 0.25000]]' %% <- incorrect values, should have been '[[-2 1][1.5 0.5]]'
```

The correct inverse matrix of L should be `'[[-2 1][1.5 -0.5]]'`, verified by R 4.1.2 and by my manual calculation.
Please check the algorithm.

**Comment by tanguyl** [comment]
Ouch... I'm sorry for this, I should have done some more thorough tests. Being a bit buzzy until Saturday, the algorithm will be corrected this weekend.

**Comment by jj1bdx** [comment]
FYI: you can use R (for statistics) to check the results of inverse-matrix calculation:

```R
> l <- matrix(c(1,3,2,4), nrow=2, ncol=2)
> l
     [,1] [,2]
[1,]    1    2
[2,]    3    4
> solve(l)
     [,1] [,2]
[1,] -2.0  1.0
[2,]  1.5 -0.5
```

**Comment by jj1bdx** [comment]
For computing an inverse matrix, using LU decomposition with LAPACKE is generally much faster and more efficient than writing your own code. An example: https://stackoverflow.com/a/41474839/417862

**Comment by tanguyl** [comment]
Thanks for the LAPACKE example! I was not able to correct my implementation, so I used that instead. 
You can find the new implementation in the branch 'debug_inv'.
I works quite well for me on Ubuntu 20.04, but I can't verify macos (lacking access to one).
Could you tell me how is it doing on your side?

**Comment by jj1bdx** [comment]
the `debug_inv` branch was tested on Mac mini 2018 (x86_64) and MacBook Air 11" M1 2020 (arm64) and both had correct results.
```erlang
src/numerl.erl:22:11: Warning: random:uniform/1 is deprecated; use the 'rand' module instead

Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace] [sharing-preserving]

Eshell V12.2  (abort with ^G)
1> L=numerl:matrix([[1,2],[3,4]]).
{matrix,2,2,
        <<0,0,0,0,0,0,240,63,0,0,0,0,0,0,0,64,0,0,0,0,0,0,8,64,0,
          ...>>}
2> Linv=numerl:inv(L).
{matrix,2,2,
        <<0,0,0,0,0,0,0,192,0,0,0,0,0,0,240,63,0,0,0,0,0,0,248,
          63,0,...>>}
3> numerl:print(Linv).
'[[-2.00000 1.00000][1.50000 -0.50000]]'
4>
```

BTW: **Please avoid using random module. random is deprecated since OTP 18. Use rand:uniform/1 instead.**

**Comment by tanguyl** [comment]
Once again, thank you for the test! New version using _rand:uniform/1_ instead of _random:uniform/1_ is available; `debug_inv` merged with the `master` branch.
