### ISSUE TITLE
Does project's erlang function not implemented?

### ISSUE THREAD

**Issue by chenyu468** [tanguyl/numerl#14]
In the numerl.erl file, most function's return " nif_not_loaded.". When it work for small array as "readme" file says?

**Comment by tanguyl** [comment]
When the numerl.erl file is loaded ( using l(numerl) if I recall correctly), the c_src/numerl.c file which defines the nif is loaded too; overriding the default behaviour of returning "nif_not_loaded".
As long as this c file is loaded, it works for small array/matrices; I hope this answers your question.
