### ISSUE TITLE
How to run the Mac system (on my M1 chip)

### ISSUE THREAD

**Issue by leeyisoft** [tanguyl/numerl#3]
How to run the Mac system (on my M1 chip)

怎么再Mac 系统运行起来（我的M1芯片的）

MacBook Pro (13-inch, M1, 2020)

**Comment by tanguyl** [comment]
Currently, I don't know. However, I'll have shortly access to a mac with a M1 ship; it should be supported within the next few days.

**Comment by tanguyl** [comment]
Some libraries used in the current 'master' branch are not available on Mac systems. 
This issue is being fixed in the "openblas" branch.

**Comment by tanguyl** [comment]
I got the library running on an M1 Macbook Air after installing openblas with brew. Could you tell me if you managed to get it working?

**Comment by tanguyl** [comment]
I received feedback it works for other persons on M1 ship; this issue is solved.
